/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'

const ScanLazyRouteImport = createFileRoute('/scan')()
const IndexLazyRouteImport = createFileRoute('/')()
const ProductIndexLazyRouteImport = createFileRoute('/product/')()
const BrandIndexLazyRouteImport = createFileRoute('/brand/')()
const UserProfileUpdateLazyRouteImport = createFileRoute(
  '/user/profile-update',
)()
const UserProfileLazyRouteImport = createFileRoute('/user/profile')()
const UserHistoryLazyRouteImport = createFileRoute('/user/history')()
const ProductProduct_idLazyRouteImport = createFileRoute(
  '/product/$product_id',
)()
const BrandBrand_idLazyRouteImport = createFileRoute('/brand/$brand_id')()
const AuthSignUpLazyRouteImport = createFileRoute('/auth/sign-up')()
const AuthSignInLazyRouteImport = createFileRoute('/auth/sign-in')()
const UserListWhiteLazyRouteImport = createFileRoute('/user/list/white')()
const UserListBlackLazyRouteImport = createFileRoute('/user/list/black')()

const ScanLazyRoute = ScanLazyRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/scan.lazy').then((d) => d.Route))
const IndexLazyRoute = IndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))
const ProductIndexLazyRoute = ProductIndexLazyRouteImport.update({
  id: '/product/',
  path: '/product/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/product/index.lazy').then((d) => d.Route))
const BrandIndexLazyRoute = BrandIndexLazyRouteImport.update({
  id: '/brand/',
  path: '/brand/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/brand/index.lazy').then((d) => d.Route))
const UserProfileUpdateLazyRoute = UserProfileUpdateLazyRouteImport.update({
  id: '/user/profile-update',
  path: '/user/profile-update',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/user/profile-update.lazy').then((d) => d.Route),
)
const UserProfileLazyRoute = UserProfileLazyRouteImport.update({
  id: '/user/profile',
  path: '/user/profile',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/user/profile.lazy').then((d) => d.Route))
const UserHistoryLazyRoute = UserHistoryLazyRouteImport.update({
  id: '/user/history',
  path: '/user/history',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/user/history.lazy').then((d) => d.Route))
const ProductProduct_idLazyRoute = ProductProduct_idLazyRouteImport.update({
  id: '/product/$product_id',
  path: '/product/$product_id',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/product/$product_id.lazy').then((d) => d.Route),
)
const BrandBrand_idLazyRoute = BrandBrand_idLazyRouteImport.update({
  id: '/brand/$brand_id',
  path: '/brand/$brand_id',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/brand/$brand_id.lazy').then((d) => d.Route),
)
const AuthSignUpLazyRoute = AuthSignUpLazyRouteImport.update({
  id: '/auth/sign-up',
  path: '/auth/sign-up',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/auth/sign-up.lazy').then((d) => d.Route))
const AuthSignInLazyRoute = AuthSignInLazyRouteImport.update({
  id: '/auth/sign-in',
  path: '/auth/sign-in',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/auth/sign-in.lazy').then((d) => d.Route))
const UserListWhiteLazyRoute = UserListWhiteLazyRouteImport.update({
  id: '/user/list/white',
  path: '/user/list/white',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/user/list/white.lazy').then((d) => d.Route),
)
const UserListBlackLazyRoute = UserListBlackLazyRouteImport.update({
  id: '/user/list/black',
  path: '/user/list/black',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/user/list/black.lazy').then((d) => d.Route),
)

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/scan': typeof ScanLazyRoute
  '/auth/sign-in': typeof AuthSignInLazyRoute
  '/auth/sign-up': typeof AuthSignUpLazyRoute
  '/brand/$brand_id': typeof BrandBrand_idLazyRoute
  '/product/$product_id': typeof ProductProduct_idLazyRoute
  '/user/history': typeof UserHistoryLazyRoute
  '/user/profile': typeof UserProfileLazyRoute
  '/user/profile-update': typeof UserProfileUpdateLazyRoute
  '/brand/': typeof BrandIndexLazyRoute
  '/product/': typeof ProductIndexLazyRoute
  '/user/list/black': typeof UserListBlackLazyRoute
  '/user/list/white': typeof UserListWhiteLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/scan': typeof ScanLazyRoute
  '/auth/sign-in': typeof AuthSignInLazyRoute
  '/auth/sign-up': typeof AuthSignUpLazyRoute
  '/brand/$brand_id': typeof BrandBrand_idLazyRoute
  '/product/$product_id': typeof ProductProduct_idLazyRoute
  '/user/history': typeof UserHistoryLazyRoute
  '/user/profile': typeof UserProfileLazyRoute
  '/user/profile-update': typeof UserProfileUpdateLazyRoute
  '/brand': typeof BrandIndexLazyRoute
  '/product': typeof ProductIndexLazyRoute
  '/user/list/black': typeof UserListBlackLazyRoute
  '/user/list/white': typeof UserListWhiteLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexLazyRoute
  '/scan': typeof ScanLazyRoute
  '/auth/sign-in': typeof AuthSignInLazyRoute
  '/auth/sign-up': typeof AuthSignUpLazyRoute
  '/brand/$brand_id': typeof BrandBrand_idLazyRoute
  '/product/$product_id': typeof ProductProduct_idLazyRoute
  '/user/history': typeof UserHistoryLazyRoute
  '/user/profile': typeof UserProfileLazyRoute
  '/user/profile-update': typeof UserProfileUpdateLazyRoute
  '/brand/': typeof BrandIndexLazyRoute
  '/product/': typeof ProductIndexLazyRoute
  '/user/list/black': typeof UserListBlackLazyRoute
  '/user/list/white': typeof UserListWhiteLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/scan'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/brand/$brand_id'
    | '/product/$product_id'
    | '/user/history'
    | '/user/profile'
    | '/user/profile-update'
    | '/brand/'
    | '/product/'
    | '/user/list/black'
    | '/user/list/white'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/scan'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/brand/$brand_id'
    | '/product/$product_id'
    | '/user/history'
    | '/user/profile'
    | '/user/profile-update'
    | '/brand'
    | '/product'
    | '/user/list/black'
    | '/user/list/white'
  id:
    | '__root__'
    | '/'
    | '/scan'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/brand/$brand_id'
    | '/product/$product_id'
    | '/user/history'
    | '/user/profile'
    | '/user/profile-update'
    | '/brand/'
    | '/product/'
    | '/user/list/black'
    | '/user/list/white'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  ScanLazyRoute: typeof ScanLazyRoute
  AuthSignInLazyRoute: typeof AuthSignInLazyRoute
  AuthSignUpLazyRoute: typeof AuthSignUpLazyRoute
  BrandBrand_idLazyRoute: typeof BrandBrand_idLazyRoute
  ProductProduct_idLazyRoute: typeof ProductProduct_idLazyRoute
  UserHistoryLazyRoute: typeof UserHistoryLazyRoute
  UserProfileLazyRoute: typeof UserProfileLazyRoute
  UserProfileUpdateLazyRoute: typeof UserProfileUpdateLazyRoute
  BrandIndexLazyRoute: typeof BrandIndexLazyRoute
  ProductIndexLazyRoute: typeof ProductIndexLazyRoute
  UserListBlackLazyRoute: typeof UserListBlackLazyRoute
  UserListWhiteLazyRoute: typeof UserListWhiteLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/scan': {
      id: '/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof ScanLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/': {
      id: '/product/'
      path: '/product'
      fullPath: '/product/'
      preLoaderRoute: typeof ProductIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand/': {
      id: '/brand/'
      path: '/brand'
      fullPath: '/brand/'
      preLoaderRoute: typeof BrandIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/profile-update': {
      id: '/user/profile-update'
      path: '/user/profile-update'
      fullPath: '/user/profile-update'
      preLoaderRoute: typeof UserProfileUpdateLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/profile': {
      id: '/user/profile'
      path: '/user/profile'
      fullPath: '/user/profile'
      preLoaderRoute: typeof UserProfileLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/history': {
      id: '/user/history'
      path: '/user/history'
      fullPath: '/user/history'
      preLoaderRoute: typeof UserHistoryLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$product_id': {
      id: '/product/$product_id'
      path: '/product/$product_id'
      fullPath: '/product/$product_id'
      preLoaderRoute: typeof ProductProduct_idLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand/$brand_id': {
      id: '/brand/$brand_id'
      path: '/brand/$brand_id'
      fullPath: '/brand/$brand_id'
      preLoaderRoute: typeof BrandBrand_idLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/auth/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/list/white': {
      id: '/user/list/white'
      path: '/user/list/white'
      fullPath: '/user/list/white'
      preLoaderRoute: typeof UserListWhiteLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/list/black': {
      id: '/user/list/black'
      path: '/user/list/black'
      fullPath: '/user/list/black'
      preLoaderRoute: typeof UserListBlackLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  ScanLazyRoute: ScanLazyRoute,
  AuthSignInLazyRoute: AuthSignInLazyRoute,
  AuthSignUpLazyRoute: AuthSignUpLazyRoute,
  BrandBrand_idLazyRoute: BrandBrand_idLazyRoute,
  ProductProduct_idLazyRoute: ProductProduct_idLazyRoute,
  UserHistoryLazyRoute: UserHistoryLazyRoute,
  UserProfileLazyRoute: UserProfileLazyRoute,
  UserProfileUpdateLazyRoute: UserProfileUpdateLazyRoute,
  BrandIndexLazyRoute: BrandIndexLazyRoute,
  ProductIndexLazyRoute: ProductIndexLazyRoute,
  UserListBlackLazyRoute: UserListBlackLazyRoute,
  UserListWhiteLazyRoute: UserListWhiteLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
